export const SERVICES = [
  { slug: 'telegram', name: 'Telegram', icon: '✈️', description: 'Receive Telegram verification codes for authorized account and testing workflows.', countries: 142 },
  { slug: 'whatsapp', name: 'WhatsApp', icon: '💬', description: 'Get WhatsApp OTP codes for account registration and verification worldwide.', countries: 138 },
  { slug: 'google', name: 'Google', icon: '🔍', description: 'Verify Google accounts, Gmail, and Google Workspace with SMS codes.', countries: 155 },
  { slug: 'instagram', name: 'Instagram', icon: '📷', description: 'Instagram SMS verification for new accounts and security checks.', countries: 130 },
  { slug: 'facebook', name: 'Facebook', icon: '👍', description: 'Facebook and Meta account verification via SMS. Fast delivery.', countries: 145 },
  { slug: 'twitter', name: 'Twitter / X', icon: '🐦', description: 'Twitter and X platform phone verification for new and existing accounts.', countries: 120 },
  { slug: 'discord', name: 'Discord', icon: '🎮', description: 'Discord phone verification to unlock full server access and features.', countries: 115 },
  { slug: 'tiktok', name: 'TikTok', icon: '🎵', description: 'TikTok account creation and verification with real phone numbers.', countries: 125 },
  { slug: 'snapchat', name: 'Snapchat', icon: '👻', description: 'Snapchat SMS verification codes delivered in seconds.', countries: 98 },
  { slug: 'linkedin', name: 'LinkedIn', icon: '💼', description: 'LinkedIn professional network phone verification and account recovery.', countries: 110 },
  { slug: 'microsoft', name: 'Microsoft', icon: '🖥️', description: 'Microsoft, Outlook, and Xbox account SMS verification codes.', countries: 148 },
  { slug: 'apple', name: 'Apple', icon: '🍎', description: 'Apple ID and iCloud verification codes via virtual numbers.', countries: 95 },
  { slug: 'amazon', name: 'Amazon', icon: '📦', description: 'Amazon account verification and two-factor authentication codes.', countries: 132 },
  { slug: 'paypal', name: 'PayPal', icon: '💳', description: 'PayPal phone verification for account setup and security.', countries: 88 },
  { slug: 'uber', name: 'Uber', icon: '🚗', description: 'Uber and Uber Eats account phone verification worldwide.', countries: 105 },
  { slug: 'netflix', name: 'Netflix', icon: '🎬', description: 'Netflix account creation with phone number verification.', countries: 92 },
  { slug: 'spotify', name: 'Spotify', icon: '🎶', description: 'Spotify music streaming account SMS verification codes.', countries: 100 },
  { slug: 'steam', name: 'Steam', icon: '🎮', description: 'Steam gaming platform phone verification and Steam Guard codes.', countries: 112 },
  { slug: 'twitch', name: 'Twitch', icon: '📺', description: 'Twitch streaming platform phone verification for creators.', countries: 85 },
  { slug: 'yahoo', name: 'Yahoo', icon: '📧', description: 'Yahoo Mail and Yahoo account SMS verification codes.', countries: 118 },
  { slug: 'line', name: 'LINE', icon: '🗨️', description: 'LINE messenger verification codes for Asian markets.', countries: 45 },
  { slug: 'viber', name: 'Viber', icon: '📞', description: 'Viber messenger account creation and phone verification.', countries: 78 },
  { slug: 'signal', name: 'Signal', icon: '🔒', description: 'Signal private messenger phone number verification.', countries: 82 },
  { slug: 'wechat', name: 'WeChat', icon: '🌏', description: 'WeChat account registration and verification for Chinese social media.', countries: 35 },
  { slug: 'binance', name: 'Binance', icon: '📈', description: 'Binance crypto exchange phone verification and 2FA setup.', countries: 96 },
  { slug: 'coinbase', name: 'Coinbase', icon: '🪙', description: 'Coinbase cryptocurrency exchange account phone verification.', countries: 72 },
  { slug: 'tinder', name: 'Tinder', icon: '🔥', description: 'Tinder dating app phone verification for new profiles.', countries: 108 },
  { slug: 'bumble', name: 'Bumble', icon: '🐝', description: 'Bumble dating app SMS verification and account creation.', countries: 75 },
  { slug: 'airbnb', name: 'Airbnb', icon: '🏠', description: 'Airbnb host and guest phone verification worldwide.', countries: 102 },
  { slug: 'openai', name: 'OpenAI', icon: '🤖', description: 'OpenAI and ChatGPT phone number verification codes.', countries: 88 },
  { slug: 'shopify', name: 'Shopify', icon: '🛒', description: 'Shopify store owner phone verification and account security.', countries: 65 },
  { slug: 'ebay', name: 'eBay', icon: '🛒', description: 'eBay marketplace account phone verification codes.', countries: 90 },
  { slug: 'revolut', name: 'Revolut', icon: '🏦', description: 'Revolut fintech app phone verification and account setup.', countries: 55 },
  { slug: 'wise', name: 'Wise', icon: '💸', description: 'Wise (TransferWise) money transfer phone verification.', countries: 68 },
  { slug: 'grab', name: 'Grab', icon: '🚕', description: 'Grab ride-hailing and delivery app phone verification in Southeast Asia.', countries: 28 },
  { slug: 'kakaotalk', name: 'KakaoTalk', icon: '💬', description: 'KakaoTalk Korean messenger phone number verification.', countries: 22 },
  { slug: 'reddit', name: 'Reddit', icon: '📝', description: 'Reddit account phone verification for full platform access.', countries: 95 },
  { slug: 'pinterest', name: 'Pinterest', icon: '📌', description: 'Pinterest social platform phone verification codes.', countries: 80 },
  { slug: 'zoom', name: 'Zoom', icon: '📹', description: 'Zoom video conferencing phone verification and 2FA codes.', countries: 110 },
  { slug: 'deliveroo', name: 'Deliveroo', icon: '🍜', description: 'Deliveroo food delivery account phone verification.', countries: 32 },
];

export const COUNTRIES = [
  { slug: 'united-states', name: 'United States', flag: '🇺🇸', iso: 'US', services: 890, phoneCode: '+1', format: '+1 (XXX) XXX-XXXX' },
  { slug: 'united-kingdom', name: 'United Kingdom', flag: '🇬🇧', iso: 'GB', services: 850, phoneCode: '+44', format: '+44 XXXX XXXXXX' },
  { slug: 'canada', name: 'Canada', flag: '🇨🇦', iso: 'CA', services: 820, phoneCode: '+1', format: '+1 (XXX) XXX-XXXX' },
  { slug: 'germany', name: 'Germany', flag: '🇩🇪', iso: 'DE', services: 780, phoneCode: '+49', format: '+49 XXX XXXXXXXX' },
  { slug: 'france', name: 'France', flag: '🇫🇷', iso: 'FR', services: 760, phoneCode: '+33', format: '+33 X XX XX XX XX' },
  { slug: 'netherlands', name: 'Netherlands', flag: '🇳🇱', iso: 'NL', services: 720, phoneCode: '+31', format: '+31 X XXXXXXXX' },
  { slug: 'russia', name: 'Russia', flag: '🇷🇺', iso: 'RU', services: 910, phoneCode: '+7', format: '+7 XXX XXX-XX-XX' },
  { slug: 'india', name: 'India', flag: '🇮🇳', iso: 'IN', services: 750, phoneCode: '+91', format: '+91 XXXXX XXXXX' },
  { slug: 'brazil', name: 'Brazil', flag: '🇧🇷', iso: 'BR', services: 680, phoneCode: '+55', format: '+55 XX XXXXX-XXXX' },
  { slug: 'indonesia', name: 'Indonesia', flag: '🇮🇩', iso: 'ID', services: 620, phoneCode: '+62', format: '+62 XXX-XXXX-XXXX' },
  { slug: 'philippines', name: 'Philippines', flag: '🇵🇭', iso: 'PH', services: 580, phoneCode: '+63', format: '+63 XXX XXX XXXX' },
  { slug: 'vietnam', name: 'Vietnam', flag: '🇻🇳', iso: 'VN', services: 540, phoneCode: '+84', format: '+84 XX XXX XX XX' },
  { slug: 'thailand', name: 'Thailand', flag: '🇹🇭', iso: 'TH', services: 560, phoneCode: '+66', format: '+66 XX XXX XXXX' },
  { slug: 'malaysia', name: 'Malaysia', flag: '🇲🇾', iso: 'MY', services: 520, phoneCode: '+60', format: '+60 XX-XXX XXXX' },
  { slug: 'ukraine', name: 'Ukraine', flag: '🇺🇦', iso: 'UA', services: 710, phoneCode: '+380', format: '+380 XX XXX XX XX' },
  { slug: 'poland', name: 'Poland', flag: '🇵🇱', iso: 'PL', services: 690, phoneCode: '+48', format: '+48 XXX XXX XXX' },
  { slug: 'spain', name: 'Spain', flag: '🇪🇸', iso: 'ES', services: 700, phoneCode: '+34', format: '+34 XXX XX XX XX' },
  { slug: 'italy', name: 'Italy', flag: '🇮🇹', iso: 'IT', services: 680, phoneCode: '+39', format: '+39 XXX XXX XXXX' },
  { slug: 'turkey', name: 'Turkey', flag: '🇹🇷', iso: 'TR', services: 640, phoneCode: '+90', format: '+90 XXX XXX XX XX' },
  { slug: 'mexico', name: 'Mexico', flag: '🇲🇽', iso: 'MX', services: 580, phoneCode: '+52', format: '+52 XX XXXX XXXX' },
  { slug: 'australia', name: 'Australia', flag: '🇦🇺', iso: 'AU', services: 720, phoneCode: '+61', format: '+61 X XXXX XXXX' },
  { slug: 'japan', name: 'Japan', flag: '🇯🇵', iso: 'JP', services: 650, phoneCode: '+81', format: '+81 XX-XXXX-XXXX' },
  { slug: 'south-korea', name: 'South Korea', flag: '🇰🇷', iso: 'KR', services: 620, phoneCode: '+82', format: '+82 XX-XXXX-XXXX' },
  { slug: 'china', name: 'China', flag: '🇨🇳', iso: 'CN', services: 480, phoneCode: '+86', format: '+86 XXX XXXX XXXX' },
  { slug: 'sweden', name: 'Sweden', flag: '🇸🇪', iso: 'SE', services: 580, phoneCode: '+46', format: '+46 XX-XXX XX XX' },
  { slug: 'norway', name: 'Norway', flag: '🇳🇴', iso: 'NO', services: 540, phoneCode: '+47', format: '+47 XXX XX XXX' },
  { slug: 'denmark', name: 'Denmark', flag: '🇩🇰', iso: 'DK', services: 520, phoneCode: '+45', format: '+45 XX XX XX XX' },
  { slug: 'finland', name: 'Finland', flag: '🇫🇮', iso: 'FI', services: 500, phoneCode: '+358', format: '+358 XX XXX XXXX' },
  { slug: 'switzerland', name: 'Switzerland', flag: '🇨🇭', iso: 'CH', services: 560, phoneCode: '+41', format: '+41 XX XXX XX XX' },
  { slug: 'austria', name: 'Austria', flag: '🇦🇹', iso: 'AT', services: 540, phoneCode: '+43', format: '+43 XXX XXXXXXX' },
  { slug: 'belgium', name: 'Belgium', flag: '🇧🇪', iso: 'BE', services: 520, phoneCode: '+32', format: '+32 XXX XX XX XX' },
  { slug: 'portugal', name: 'Portugal', flag: '🇵🇹', iso: 'PT', services: 500, phoneCode: '+351', format: '+351 XXX XXX XXX' },
  { slug: 'czech-republic', name: 'Czech Republic', flag: '🇨🇿', iso: 'CZ', services: 480, phoneCode: '+420', format: '+420 XXX XXX XXX' },
  { slug: 'romania', name: 'Romania', flag: '🇷🇴', iso: 'RO', services: 460, phoneCode: '+40', format: '+40 XXX XXX XXX' },
  { slug: 'hungary', name: 'Hungary', flag: '🇭🇺', iso: 'HU', services: 440, phoneCode: '+36', format: '+36 XX XXX XXXX' },
  { slug: 'argentina', name: 'Argentina', flag: '🇦🇷', iso: 'AR', services: 420, phoneCode: '+54', format: '+54 XX XXXX-XXXX' },
  { slug: 'colombia', name: 'Colombia', flag: '🇨🇴', iso: 'CO', services: 400, phoneCode: '+57', format: '+57 XXX XXX XXXX' },
  { slug: 'chile', name: 'Chile', flag: '🇨🇱', iso: 'CL', services: 380, phoneCode: '+56', format: '+56 X XXXX XXXX' },
  { slug: 'nigeria', name: 'Nigeria', flag: '🇳🇬', iso: 'NG', services: 420, phoneCode: '+234', format: '+234 XXX XXX XXXX' },
  { slug: 'south-africa', name: 'South Africa', flag: '🇿🇦', iso: 'ZA', services: 450, phoneCode: '+27', format: '+27 XX XXX XXXX' },
  { slug: 'egypt', name: 'Egypt', flag: '🇪🇬', iso: 'EG', services: 380, phoneCode: '+20', format: '+20 XX XXXX XXXX' },
  { slug: 'kenya', name: 'Kenya', flag: '🇰🇪', iso: 'KE', services: 340, phoneCode: '+254', format: '+254 XXX XXXXXX' },
  { slug: 'israel', name: 'Israel', flag: '🇮🇱', iso: 'IL', services: 480, phoneCode: '+972', format: '+972 XX-XXX-XXXX' },
  { slug: 'uae', name: 'United Arab Emirates', flag: '🇦🇪', iso: 'AE', services: 460, phoneCode: '+971', format: '+971 XX XXX XXXX' },
  { slug: 'saudi-arabia', name: 'Saudi Arabia', flag: '🇸🇦', iso: 'SA', services: 420, phoneCode: '+966', format: '+966 XX XXX XXXX' },
  { slug: 'singapore', name: 'Singapore', flag: '🇸🇬', iso: 'SG', services: 540, phoneCode: '+65', format: '+65 XXXX XXXX' },
  { slug: 'hong-kong', name: 'Hong Kong', flag: '🇭🇰', iso: 'HK', services: 500, phoneCode: '+852', format: '+852 XXXX XXXX' },
  { slug: 'new-zealand', name: 'New Zealand', flag: '🇳🇿', iso: 'NZ', services: 460, phoneCode: '+64', format: '+64 XX XXX XXXX' },
  { slug: 'ireland', name: 'Ireland', flag: '🇮🇪', iso: 'IE', services: 480, phoneCode: '+353', format: '+353 XX XXX XXXX' },
  { slug: 'greece', name: 'Greece', flag: '🇬🇷', iso: 'GR', services: 420, phoneCode: '+30', format: '+30 XXX XXX XXXX' },
  { slug: 'pakistan', name: 'Pakistan', flag: '🇵🇰', iso: 'PK', services: 380, phoneCode: '+92', format: '+92 XXX XXXXXXX' },
  { slug: 'bangladesh', name: 'Bangladesh', flag: '🇧🇩', iso: 'BD', services: 340, phoneCode: '+880', format: '+880 XXXX-XXXXXX' },
  { slug: 'peru', name: 'Peru', flag: '🇵🇪', iso: 'PE', services: 320, phoneCode: '+51', format: '+51 XXX XXX XXX' },
  { slug: 'kazakhstan', name: 'Kazakhstan', flag: '🇰🇿', iso: 'KZ', services: 440, phoneCode: '+7', format: '+7 XXX XXX XX XX' },
];

export const BASE_URL = 'https://ringslot.shop';

export function getServiceBySlug(slug) {
  return SERVICES.find(s => s.slug === slug) || null;
}

export function getCountryBySlug(slug) {
  return COUNTRIES.find(c => c.slug === slug) || null;
}
